name: mobilelegendguide
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.4.5
  flutter_slidable: ^0.6.0
  firebase_core: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/heroes.csv
    - asset/lane/
    - asset/classes/
    - asset/items/
    - asset/emblems/
    - asset/skills/
